LOAD_LINUX=$(ROOT_DIR)/load-linux.sh
LOAD_OPTS=--tftp

sync-drafts:
	rsync -avzr $(RESOURCES_DIR)/* $(DRAFTS_DIR)

.PHONY:
device-reset: sync-drafts sdk
	$(LOAD_LINUX) --reset

.PHONY:
device-reload: sdk device-reset
	$(LOAD_LINUX) $(LOAD_OPTS) --no-minicom

.PHONY:
xmd-shell:
	@echo "Default xmd commands:"
	$(LOAD_LINUX) --show-xmd-commands
	$(LOAD_LINUX) --xmd-shell

.PHONY:
minicom:
	$(LOAD_LINUX) --minicom
