SDK_FILES = $(RESOURCES_DIR)/stub.tcl \
	$(RESOURCES_DIR)/hdmi.tcl \
	$(RESOURCES_DIR)/ps7_init.tcl \
	$(RESOURCES_DIR)/bitstream.bit \
	$(RESOURCES_DIR)/fsbl.bin

.PHONY:
sdk:$(SDK_FILES)

.SECONDEXPANSION:
$(SDK_FILES): $$(@:$(RESOURCES_DIR)=$(DATA_DIR))
	cp $< $@
