* Usage
** Cleanup
   For archives you can run for exaple:
   #+BEGIN_EXAMPLE
   make libpng-clean-archive
   #+END_EXAMPLE

   To remove all traces of libpng (except from the filesystem)
** Threads
   To compile directfb with 4 threads do.
   #+BEGIN_EXAMPLE
   make MAKETHREADS=4 dfb-all
   #+END_EXAMPLE

   This converts all calls to =make= into =make -j4=.
** DirectFB
   To build everything run

   #+BEGIN_EXAMPLE
   make dfb-all
   #+END_EXAMPLE

** Nfsroot
   For now we do not have proper nfsroot but there is a script you can
   run to get root at your fs.

   #+BEGIN_EXAMPLE
   /homes/zynqfs/init.sh
   #+END_EXAMPLE

   That will run the init scripts as expected.

** Debug
   You may run =debug.sh <program-in-bin>= to debug something running
   on the board's gdbserver.

   From the board look for =dbi.sh <program to debug>= if you cant
   bother to look into gdb server.

** Lazy
   The problem when a makefile compiles a couple of other projects is
   that =./configure= will always run and may take quite some time
   when phony targets are being run. So each target
   =target-name-build= has an enquivalent =target-name-lazy= which
   will run =target-name-build= if there is not token file in =lazy/=
   and then create such a file. This way we can avoid configuring
   things like =libjpeg= again and again.

   For example:

   #+BEGIN_EXAMPLE
   make linux-lazy
   #+END_EXAMPLE

   will run =make linux-build= and then it will create a file. If we
   try to run again =make linux-lazy= it will just skip it.

   #+BEGIN_EXAMPLE
   make linux-clean-lazy
   #+END_EXAMPLE

   cleans the created files by lazy

   #+BEGIN_EXAMPLE
   make all-clean-lazy
   #+END_EXAMPLE

   clears all laziness.

   If you are sure you have run =linux-build= or for any reason you
   want to prevent a lazy from actually doing anything you can run.

   #+BEGIN_EXAMPLE
   make linux-shallow-lazy
   #+END_EXAMPLE

   to create the lazy file without building (again)

** Hardware
*** SD Card usage
    To use the sd card loaded stuff the switches must be:

    |    1 |    2 |  3 |  4 |    5 |
    |------+------+----+----+------|
    | Down | Down | Up | Up | Down |

*** JTAG usage
    To load linux from the jtag you must have all switches down

    |    1 |    2 |    3 |    4 |    5 |
    |------+------+------+------+------|
    | Down | Down | Down | Down | Down |

    For ZC702 you also need to setup SW10

    | JTAG Mode             | Switch 0 | Switch 1 |
    |-----------------------+----------+----------|
    | Invalid               | off      | off      |
    | Digilent USB JTAG     | off      | on       |
    | Xilinx Platform Cable | on       | off      |
    | 20-pin Header         | off      | off      |

* Notes
  MODULEDIR is absolute for host.
